JZsGreen/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JZsGreen.Data;
using JZsGreen.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using X.PagedList;
using Microsoft.IdentityModel.Tokens;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.OutputCaching;

namespace JZsGreen.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {

        private readonly JZenoDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductsController(JZenoDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        [Route("Admin/Products")]
        [OutputCache(NoStore = true, Duration = 10)]
        public async Task<IActionResult> Index()
        {
            var product = await _context.Product.Include(e => e.Category).ToListAsync();
            return View(product);
        }

        [Route("Admin/Products/Create")]
        public IActionResult Create()
        {
            Product product = new Product();
            var autoID = _context.Product.OrderByDescending(c => c.Id).FirstOrDefault();
            var lPro = _context.Product.ToList();
            if (autoID == null)
            {
                product.Id = "JZENO1";
            }
            else
            {
                product.Id = "JZENO" + (lPro.Count + 1).ToString();
            }
            ViewData["categoryID"] = new SelectList(_context.CategoryChildren, "Id", "name");
            return View(product);
        }

        [Route("Admin/Products/Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,name,price,unit,quantity,discount,totalPrice,isActive,summary,description,files,categoryId")] Product product)
        {
            foreach (var item in product.files!)
            {
                string stringFileName = UploadFile(item);
                var productImgs = new ProductImage
                {
                    id = Guid.NewGuid().ToString(),
                    fileName = stringFileName,
                    Product = product
                };
                _context.Add(productImgs);
            }

            if (ModelState.IsValid)
            {
                if (product.discount == null) product.discount = 0;
                if (product.description == null) product.description = "Chưa cập nhật";
                if (product.price < 0) product.price = Math.Abs(product.price.Value);
                product.isActive = true;
                product.dateCreated = DateTime.Now;
                product.totalPrice = product.price - (product.price * (product.discount / 100));
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["categoryID"] = new SelectList(_context.CategoryChildren, "Id", "name");
            return View(product);
        }

        [Route("Admin/Products/Edit/{id?}")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }
            var product = await _context.Product.Include(e => e.images).FirstOrDefaultAsync(i => i.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["categoryID"] = new SelectList(_context.CategoryChildren, "Id", "name");
            return View(product);
        }


        [Route("Admin/Products/Edit/{id?}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,name,unit,price,quantity,discount,totalPrice,isActive,summary,description,files,categoryId")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }
            var productImg = _context.ProductImage.Where(m => m.productId == id);
            if (productImg != null)
            {
                foreach (var item in productImg)
                {
                    if (!product.files!.IsNullOrEmpty())
                    {
                        DeleteFile(item.fileName!);
                        _context.Remove(item);
                    }
                }
            }
            foreach (var item in product.files!)
            {
                string stringFileName = UploadFile(item);
                var productImgs = new ProductImage
                {
                    id = Guid.NewGuid().ToString(),
                    fileName = stringFileName,
                    productId = product.Id
                };
                _context.Add(productImgs);
            }
            if (ModelState.IsValid)
            {
                try
                {
                    product.dateCreated = DateTime.Now;
                    product.totalPrice = product.price - (product.price * (product.discount / 100));
                    if (product.quantity > 0)
                    {
                        product.isActive = true;
                    }
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["categoryID"] = new SelectList(_context.CategoryChildren, "Id", "name");
            return View(product);
        }
        [Route("/Admin/Products/updateActive/{id?}")]
        public async Task<JsonResult> updateActive(string id)
        {
            var product = await _context.Product.FindAsync(id);

            if (ModelState.IsValid)
            {
                try
                {
                    if (product!.isActive == null) product.isActive = true;
                    else product!.isActive = !product!.isActive;
                    product.dateCreated = DateTime.Now;
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                }
                return Json(product);
            }
            return Json(product);
        }

        [Route("Admin/Products/Delete/{id?}")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }
            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [Route("Admin/Products/Delete/{id?}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Product == null)
            {
                return Problem("Entity set 'JZenoDbContext.Products'  is null.");
            }
            var proImg = await _context.ProductImage.Where(e => e.productId == id).FirstOrDefaultAsync();
            var product = await _context.Product.FindAsync(id);
            if (product != null)
            {
                _context.ProductImage.Remove(proImg!);
                _context.Product.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(string id)
        {
            return (_context.Product?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        private void DeleteFile(string file)
        {
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\products", file);

            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
        }
        private string UploadFile(IFormFile file)
        {
            string? fileName = null;
            if (file != null)
            {
                string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "images/products");
                fileName = Guid.NewGuid().ToString() + "-" + file.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
            }
            return fileName!;
        }
    }
}

JZsGreen/Areas/Admin/Controllers/UserController.cs
using JZsGreen.Data;
using JZsGreen.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace JZsGreen.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly JZenoDbContext _context;
        public UserController(UserManager<User> userManager, SignInManager<User> signInManager, JZenoDbContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        [Route("Admin/User")]
        public IActionResult Index()
        {
            var user = _userManager.Users.ToList();
            return View(user);
        }
        public ActionResult lockOut(string? id)
        {
            var user = _userManager.Users.ToList().FirstOrDefault(e => e.Id == id);
            user!.LockoutEnabled = true;
            user!.LockoutEnd = DateTime.Now.AddDays(30);
            _context.Update(user);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public ActionResult unLock(string? id)
        {
            var user = _userManager.Users.ToList().FirstOrDefault(e => e.Id == id);
            user!.LockoutEnabled = false;
            user!.LockoutEnd = DateTime.Now;
            _context.Update(user);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public ActionResult UpdatePoint(string? id)
        {
            var user = _userManager.Users.ToList().FirstOrDefault(e => e.Id == id);
            user!.point = 0;
             _context.Update(user);
             _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

JZsGreen/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JZsGreen.Data;
using JZsGreen.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace JZsGreen.Controllers
{
    public class BillsController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly JZenoDbContext _context;

        public BillsController(JZenoDbContext context, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        // GET: Bills
        [Route("Bill/list")]
        public async Task<IActionResult> Index(string searchPhone)
        {
            ViewData["GetPhone"] = searchPhone;
            if (_signInManager.IsSignedIn(User) == true)
            {
                searchPhone = _userManager.GetUserAsync(User).Result!.PhoneNumber!;
            }
            var jZenoDbContext = _context.Bill.Where(e=>e.phone == searchPhone).OrderByDescending(e=>e.date).Include(b => b.User);
            return View(await jZenoDbContext.ToListAsync());
        }
        // GET: Bills/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Bill == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill
                .Include(b => b.User)
                .Include(b=>b.detailsOrders)!.ThenInclude(e=>e.product).ThenInclude(e=>e!.images)
                .FirstOrDefaultAsync(m => m.billID == id);
            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }
        public IActionResult ActivePoint(string id)
        {
           if(_signInManager.IsSignedIn(User) == true)
            {
                var point = _userManager.GetUserAsync(User).Result!.point;
                var userMail = User.FindFirstValue(ClaimTypes.Email);
                var user = _userManager.Users.ToList().FirstOrDefault(e => e.Email == userMail);
                var bill = _context.Bill.ToList().FirstOrDefault(m => m.billID == id);
                bill!.point = point;
                bill!.totalPrice -= point;
                user!.point = 0;
                _context.Update(user);
                _context.Update(bill);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

JZsGreen/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" type="image/x-icon" href="~/images/fixed/logoJZ.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JZsGreen.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/home.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/detail.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bill.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/DetailReadMore.js" asp-append-version="true"></script>
    <script src="~/js/ApiTinyMCE.js" asp-append-version="true"></script>
    <script src="~/js/ProductLoad.js" asp-append-version="true"></script>
    <script src="~/js/BillLoad.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <script asp-append-version="true" src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script asp-append-version="true" src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
</head>
<body class="bg-white">
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0" style="background: #198754;">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline text-center"></span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li class="nav-item">
                            <a href="/" class="nav-link align-middle px-0">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Trang Chủ</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-area="Admin" asp-controller="Home" class="nav-link align-middle px-0">
                                <i class="fs-4 bi-bar-chart"></i> <span class="ms-1 d-none d-sm-inline">Thống Kê</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-area="Admin" asp-controller="User" class="nav-link align-middle px-0">
                                <i class="fs-4 bi-people-fill"></i> <span class="ms-1 d-none d-sm-inline">Người Dùng</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-area="Admin" asp-controller="Bills" class="nav-link align-middle px-0">
                                <i class="fs-4 bi-bag-check-fill"></i> <span class="ms-1 d-none d-sm-inline">Quản Lý Đơn Hàng</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-area="Admin" asp-controller="Products" class="nav-link align-middle px-0">
                                <i class="fs-4 bi-boxes"></i> <span class="ms-1 d-none d-sm-inline">Quản Lý Sản Phẩm</span>
                            </a>
                        </li>

                        <li>
                            <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Quản Lý Danh Mục</span>
                            </a>
                            <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                                <li class="w-100">
                                    <a asp-action="Index" asp-area="Admin" asp-controller="Categories" class="nav-link px-0"><i class="fs-4 bi-inbox"></i><span class="d-none d-sm-inline"> Danh Mục Lớn</span></a>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-area="Admin" asp-controller="CategoryChilds" class="nav-link px-0"><i class="fs-4 bi-inboxes"></i><span class="d-none d-sm-inline"> Danh Mục Nhỏ</span></a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <hr />
                    <div class="dropdown pb-4">
                        <div class="nav-item">
                            <a asp-area="Identity" asp-page="/Account/Manage/Index" class="nav-link fw-bold text-white align-middle px-0">
                                <i class="fs-4 bi-person"></i> <span class="ms-1 d-none d-sm-inline">Thông Tin Cá Nhân</span>
                            </a>
                        </div>
                        <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button style="color:white; font-weight:bold; border:none; background:transparent" type="submit" class="nav-link px-0 align-middle"><i class="fs-4 bi-box-arrow-left"></i><span class="ms-1 d-none d-sm-inline"> Đăng xuất</span></button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col py-3">
                @RenderBody()
            </div>
        </div>
        @await RenderSectionAsync("Scripts", required: false)
        @{
            //   await Html.RenderPartialAsync("_AuthScriptsPartial");
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    </div>
</body>
</html>
<style>
    body {
        margin: 0 !important;
    }

    #menu li a {
        color: white;
        font-weight: bold;
    }

    h1 {
        text-align: center;
    }
</style>