JZsGreen/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JZsGreen.Data;
using JZsGreen.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace JZsGreen.Controllers
{
    public class BillsController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly JZenoDbContext _context;

        public BillsController(JZenoDbContext context, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        // GET: Bills
        [Route("Bill/list")]
        public async Task<IActionResult> Index(string searchPhone)
        {
            ViewData["GetPhone"] = searchPhone;
            if (_signInManager.IsSignedIn(User) == true)
            {
                searchPhone = _userManager.GetUserAsync(User).Result!.PhoneNumber!;
            }
            var jZenoDbContext = _context.Bill.Where(e=>e.phone == searchPhone).OrderByDescending(e=>e.date).Include(b => b.User);
            return View(await jZenoDbContext.ToListAsync());
        }
        // GET: Bills/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Bill == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill
                .Include(b => b.User)
                .Include(b=>b.detailsOrders)!.ThenInclude(e=>e.product).ThenInclude(e=>e!.images)
                .FirstOrDefaultAsync(m => m.billID == id);
            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }
        public IActionResult ActivePoint(string id)
        {
           if(_signInManager.IsSignedIn(User) == true)
            {
                var point = _userManager.GetUserAsync(User).Result!.point;
                var userMail = User.FindFirstValue(ClaimTypes.Email);
                var user = _userManager.Users.ToList().FirstOrDefault(e => e.Email == userMail);
                var bill = _context.Bill.ToList().FirstOrDefault(m => m.billID == id);
                bill!.point = point;
                bill!.totalPrice -= point;
                user!.point = 0;
                _context.Update(user);
                _context.Update(bill);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

JZsGreen/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using JZsGreen.Data;
using Microsoft.AspNetCore.OutputCaching;
using X.PagedList;

namespace JZsGreen.Controllers
{
    public class ProductController : Controller
    {
        private readonly JZenoDbContext _context;

        public ProductController(JZenoDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(string id, string searchName,string discount, int? page)
        {
            ViewData["GetData"] = searchName;
            ViewData["GetDiscount"] = discount;
            ViewData["GetPro"] = await _context.Category.Include(e => e.CategoryChild).ToListAsync();
            var product = from b in _context.Product
                          select b;
            if (searchName != null && id == null && discount == null)
            {
                product = product.Where(e => e.name!.Contains(searchName));
            }
            else if (searchName == null && id != null  && discount == null)
            {
                ViewData["GetTitle"] = id;
                product = product.Where(e => e.Category!.name!.Contains(id));
            }
            else if (searchName != null && id == null && discount == null)
            {
                product = product.Where(e => e.name!.Contains(searchName) && e.Category!.name!.Contains(id!));
            }
            else if (searchName == null && id == null && discount != null)
            {
                product = product.Where(e => e.discount > 0);
            }
            else if (searchName == null && id != null && discount != null)
            {
                ViewData["GetTitle"] = id;
                product = product.Where(e => e.discount > 0 && e.Category!.name!.Contains(id));
            }
            else if (searchName != null && id == null && discount != null)
            {
                product = product.Where(e=> e.name!.Contains(searchName) && e.discount > 0);
            }
            else if (searchName != null || id != null || discount != null)
            {
                ViewData["GetTitle"] = id;
                product = product.Where(e => e.name!.Contains(searchName!) && e.discount > 0 && e.Category!.name!.Contains(id!));
            }
            return View(await product.Include(e=>e.images).OrderByDescending(e=>e.isActive).ToPagedListAsync(page ?? 1, 12));

        }
        
        public async Task<JsonResult> GetNameList()
        {
            var productList = await _context.Product.Select(e=>e.name).ToListAsync();
            return Json(productList);
        }
        public async Task<IActionResult> SideBar()
        {
            var category = await _context.Category.OrderByDescending(e=>e.Id).Include(e => e.CategoryChild)!.ThenInclude(e => e.Products).ToListAsync();
            return PartialView("SideBar", category);
        }
        [Route("SanPham/{id}")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product.Include(e => e.Category).ThenInclude(e => e.Products)!.ThenInclude(e => e.images).Include(e => e.images)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }
    }
}

JZsGreen/Controllers/UserAuthController.cs
using JZsGreen.Data;
using JZsGreen.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace JZsGreen.Controllers
{
    public class UserAuthController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly JZenoDbContext _context;

        public UserAuthController(JZenoDbContext context,
                                  UserManager<User> userManager,
                                  SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel loginModel)
        {
            loginModel.LoginInValid = "true";

            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(loginModel.UserName!,
                                                                     loginModel.Pass!,
                                                                     loginModel.RememberMe,
                                                                     lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    loginModel.LoginInValid = "";
                }
                if (result.IsLockedOut)
                {
                    ModelState.AddModelError(string.Empty, "Tài Khoản của bạn đã bị khóa");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Vui lòng kiểm tra tài khoản hoặc mật khẩu");
                }

            }
            return PartialView("_UserLoginPartial", loginModel);

        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();

            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }


          [AllowAnonymous]
         [HttpPost]
         [ValidateAntiForgeryToken]
         public async Task<IActionResult> RegisterUser(RegistrationModel registrationModel)
         {

             if (ModelState.IsValid)
             {
                User user = new User
                {
                    Id = Guid.NewGuid().ToString(),
                    UserName = registrationModel.Email,
                    Email = registrationModel.Email,
                    NormalizedEmail = registrationModel.Email!.ToUpper(),
                    PhoneNumber = registrationModel.PhoneNumber,
                    fullName = registrationModel.FullName,
                    dateCreated = DateTime.Now,
                    LockoutEnabled = false,
                    point = 0
                 };

                 var result = await _userManager.CreateAsync(user, registrationModel.Password!);

                if (result.Succeeded)
                {
                    registrationModel.RegistrationInValid = "";

                    await _signInManager.SignInAsync(user, isPersistent: false);
                    _userManager.AddToRoleAsync(user, "Customer").Wait();

                    return PartialView("_UserRegistrationPartial", registrationModel);
                }

                AddErrorsToModelState(result);

            }
            return PartialView("_UserRegistrationPartial", registrationModel);

        }

        [AllowAnonymous]
         public async Task<bool> UserNameExists(string userName)
         {
             bool userNameExists = await _context.Users.AnyAsync(u => u.UserName!.ToUpper() == userName.ToUpper());

             if (userNameExists)
                 return true;

             return false;

         }

         private void AddErrorsToModelState(IdentityResult result)
         {
             foreach (var error in result.Errors)
                 ModelState.AddModelError(string.Empty, error.Description);
         }    
    }
}

JZsGreen/Views/Shared/_CartPartial.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@inject IHttpContextAccessor HttpContextAccessor

<a class="item-cart" id="cart-title" asp-route="cart">
    <span style="color:white"><i class="fa fa-shopping-cart" id="cartCount"></i> Giỏ Hàng</span>
</a>

JZsGreen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" type="image/x-icon" href="~/images/fixed/logoJZ.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JZsGreen.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/home.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/detail.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/cart.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/DetailReadMore.js" asp-append-version="true"></script>
    <script src="~/js/ProductLoad.js" asp-append-version="true"></script>
    <script src="~/js/CartReload.js" asp-append-version="true"> </script>
    <script src="~/js/UserLogin.js" asp-append-version="true"></script>
    <script src="~/js/UserRegistration.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <script src="~/js/autoSearch.js" asp-append-version="true"></script>

</head>
<body>
  <div>
        <header>
            <nav id="navbar" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-success border-bottom box-shadow mb-3 fixed-top">
                <div class="container-fluid container">
                    <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">MSMS</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Trang Chủ</a>
                            </li>
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
                <div class="row" style="margin-top:3px; margin-bottom:3px;">
                    <div class="col-md-3 col-sm"></div>
                    <div class="col-md col-sm-8 col-xl">
                        <form asp-controller="Product" asp-action="Index" method="get" class="input-group inputSearch col" style="flex-wrap:nowrap; justify-content: center;">
                            <div id="search-autocomplete" style="width:100%;" class="form-outline">
                                <input type="search" value="@ViewData["GetData"]" style="height:100%" id="search" name="searchName" class="form-control textbox" placeholder="Tìm kiếm..." />
                            </div>
                            <button class="btn bg-warning">
                                <i class="fa fa-search"></i>
                            </button>
                        </form>
                    </div>
                    <div class="col-md-3 col-sm">
                    </div>
                </div>
            </nav>
        </header>


        @{
            @await Html.PartialAsync("_CartPartial")
        }
        <div id="height-body"></div>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        <div id="space-footer"></div>
        <footer class="text-center text-lg-start text-dark w-100"
                style="background-color: #198754; position:absolute; bottom:0">
            <section class="text-white">
                <div class="container text-center text-md-start mt-5" style="padding:5px;">
                    <div class="row mt-3">
                        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                            <h6 class="text-uppercase fw-bold">JZsGreen</h6>
                            <hr class="mb-4 mt-0 d-inline-block mx-auto"
                                style="width: 60px; background-color: white; height: 2px" />
                            <p>
                                Chào mừng bạn đến với JZsGreen
                            </p>
                            <p>
                                Chúc bạn có 1 ngày thật vui vẻ và nhiều may mắn
                            </p>
                        </div>
                        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                            <h6 class="text-uppercase fw-bold">Lựa Chọn</h6>
                            <hr class="mb-4 mt-0 d-inline-block mx-auto"
                                style="width: 60px; background-color: white; height: 2px" />
                            <p>
                                <a href="../Product/Index" class="text-white">Hàng Mới</a>
                            </p>
                            <p>
                                <a href="../Product?discount=Hàng+Giảm+Giá" class="text-white">Hàng Giảm Giá</a>
                            </p>
                        </div>
                        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                            <h6 class="text-uppercase fw-bold">Liên Hệ</h6>
                            <hr class="mb-4 mt-0 d-inline-block mx-auto"
                                style="width: 60px; background-color: white; height: 2px" />
                            <p>
                                <a href="https://www.facebook.com/profile.php?id=100031925508672" class="text-white">
                                    <i class="bi-facebook text-white"></i>  Thanh Phong
                                </a>
                            </p>
                            <p>
                                <a href="https://www.instagram.com/t.ph15?igsh=MTJiN2NvYWp0b2NtNA%3D%3D" class="text-white">
                                    <i class="bi-instagram text-white"></i>  Thanh Phong
                                </a>
                            </p>
                            <p>
                                <a href="tel:+84819003999" class="text-white">
                                    <i class="bi-phone text-white"></i> +84 819 003 999
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </section>
        </footer>
  </div>
    <div class="modal fade" id="UserLoginModal" tabindex="-1" role="dialog" data-bs-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <partial name="_UserLoginPartial" model="new LoginModel
        {
            UserName = String.Empty,
            Pass = String.Empty,
            RememberMe = false
        }">
    </div>

    <div class="modal fade" id="UserRegistrationModal" tabindex="-1" data-bs-backdrop="static" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <partial name="_UserRegistrationPartial" model="new RegistrationModel
        {
            Email = String.Empty,
            Password = String.Empty,
            ConfirmPassword = String.Empty,
            FullName = String.Empty,
            PhoneNumber = String.Empty,
            AcceptUserAgreement = false
        }">
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" data-bs-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content" style="border-radius:16px; padding:5px;">
                <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLabel">Đơn Hàng Của Bạn</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <h5>
                        Để xem "Đơn hàng của bạn" vui lòng
                        nhập Số điện thoại đã đặt hàng
                    </h5>
                    <form asp-controller="Bills" asp-action="Index" method="get" class="input-group col" style="justify-content: center;margin-top:30px;">
                        <div id="search-autocomplete" class="form-outline input-container" style="width:100%; align-items:center;">
                             <i class="fa fa-phone icon"></i>
                            <input required minlength="10" maxlength="10" pattern="[0-9]{10}" type="search" value="@ViewData["GetPhone"]" name="searchPhone" class="input-field" placeholder="Nhập số điện thoại của bạn" />
                        </div>
                        <button class="btn btn-primary" style="width:100%; margin: 15px 0; color:white; font-weight:bold;"><i class="fa fa-search"></i> Tra cứu</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @await RenderSectionAsync("Scripts", required: false)
    @{
        //await Html.RenderPartialAsync("_AuthScriptsPartial");
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

</body>
</html>
<style>
    /* Style the input container */
    .input-container {
        display: flex;
        width: 100%;
        margin-bottom: 15px;
    }

    /* Style the form icons */
    .icon {
        min-width: 50px;
        border: 0.5px solid;
        padding:11px;
        font-size:20px;
        font-weight:bold;
        text-align: center;
    }

    /* Style the input fields */
    .input-field {
        width: 100%;
        padding: 10px;
        outline: none;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #212529;
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
    }

</style>

JZsGreen/Views/Shared/_UserLoginPartial.cshtml
@model JZsGreen.Models.LoginModel

<div class="modal-dialog modal-dialog-centered" tabindex="-1">
    <div class="modal-dialog row d-flex justify-content-center align-items-center" style="width:500px">
        <div class="modal-content" style="border-radius:16px">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Đăng Nhập</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" style="padding: 30px;">
                <div id="alert_placeholder_login">
                </div>
                <form id="UserLoginForm" asp-controller="UserAuth" asp-action="Login">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="LoginInValid">
                    <div class="form-group row">
                        <input asp-for="UserName" placeholder="Email" class="form-control my-2">
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <input asp-for="Pass" placeholder="Mật Khẩu" class="form-control my-2">
                        <span asp-validation-for="Pass" class="text-danger"></span>
                    </div>
                    <div class="form-group-row">
                        <div class="form-check">
                            <input asp-for="RememberMe" class="form-check-input" checked>
                            <label asp-for="RememberMe" class="form-check-label"></label>
                        </div>
                    </div>
                </form>
            </div>
            <button type="button" id="login" name="login" class="btn btn-primary" style="margin:25px">Đăng Nhập</button>
        </div>
    </div>
</div>

JZsGreen/Views/Shared/_UserRegistrationPartial.cshtml
@model JZsGreen.Models.RegistrationModel

<div class="modal-dialog modal-dialog-centered" tabindex="-1" role="document">
    <div class="modal-dialog row d-flex justify-content-center align-items-center" style="width:500px">
        <div class="modal-content" style="border-radius:16px">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Đăng Ký</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" style="padding: 30px;">
                <div id="alert_placeholder_register">
                </div>
                <form id="UserRegistrationForm" name="UserRegistrationForm" asp-controller="UserAuth" asp-action="RegisterUser">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="RegistrationInValid">
                    <div class="form-group row">
                        <input asp-for="Email" placeholder="Email" class="form-control my-2">
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <input asp-for="Password" required placeholder="Mật khẩu" class="form-control my-2">
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <input asp-for="ConfirmPassword" required placeholder="Xác nhận mật khẩu" class="form-control my-2">
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <input asp-for="FullName" required placeholder="Họ tên" class="form-control my-2">
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <input asp-for="PhoneNumber" required pattern="[0-9]{10}" minlength="10" maxlength="10" placeholder="Số Điện Thoại" class="form-control my-2">
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <input asp-for="AcceptUserAgreement" class="form-check-input" checked hidden>
                </form>
            </div>
            <button id="register" name="register" type="button" class="btn btn-primary" style="margin:25px">Tạo Tài Khoản</button>
        </div>
    </div>
</div>